#  _______ .___________. _______ .______      .__   __.  __       ___
# |   ____||           ||   ____||   _  \     |  \ |  | |  |     /   \
# |  |__   `---|  |----`|  |__   |  |_)  |    |   \|  | |  |    /  ^  \
# |   __|      |  |     |   __|  |      /     |  . `  | |  |   /  /_\  \
# |  |____     |  |     |  |____ |  |\  \----.|  |\   | |  |  /  _____  \
# |_______|    |__|     |_______|| _| `._____||__| \__| |__| /__/     \__\


sql:
  table-marry: 'es_marry'
  table-bank: 'es_marryBank'

server:
  cooldown: 4

money:
  marry: 500000
  sethome: 5000