main: br.com.eterniaserver.eterniamarriage.EterniaMarriage

name: EterniaMarriage
version: '${project.version}'
author: Yuri Nogueira
description: Casamentu
api-version: '1.13'
depend: [EterniaLib, Vault, PlaceholderAPI]